try:
	import pass_one
	import pass_two

except Exception as e:
	print(e)